export const PERMISSION = [
  // 值班记录
  {
    uid: "1",
    resourceName: "值班记录单",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconbianzu17",
    routeName: "",
  },
  {
    uid: "011",
    resourceName: "值班记录首页",
    parentUid: "1",
    resourceLayer: 3,
    style: "icon_1",
    routeName: "ondutymain",
  },
  {
    uid: "012",
    resourceName: "值班记录列表",
    parentUid: "1",
    resourceLayer: 3,
    style: "icon_1",
    routeName: "ondutylist",
  },
  {
    uid: "013",
    resourceName: "所有工作记录",
    parentUid: "1",
    resourceLayer: 3,
    style: "icon_1",
    routeName: "ondutyall",
  },
  // 信息处理
  {
    uid: "2",
    resourceName: "信息处理",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconbianzu18",
    routeName: "",
  },
  {
    uid: "321",
    resourceName: "接报值班信息",
    parentUid: "2",
    resourceLayer: 3,
    style: "",
    routeName: "receiveDutyInformation",
  },
  {
    uid: "322",
    resourceName: "要情快报",
    parentUid: "2",
    resourceLayer: 3,
    style: "",
    routeName: "importantExpress",
  },
  {
    uid: "323",
    resourceName: "上报值班信息",
    parentUid: "2",
    resourceLayer: 3,
    style: "",
    routeName: "updateDutyInformation",
  },
  {
    uid: "324",
    resourceName: "接收抄送信息",
    parentUid: "2",
    resourceLayer: 3,
    style: "",
    routeName: "acceptCCInfo",
  },
  {
    uid: "325",
    resourceName: "已退回信息",
    parentUid: "2",
    resourceLayer: 3,
    style: "",
    routeName: "alreadyBackInfo",
  },
  
  // 领导批示办理
  {
    uid: "3",
    resourceName: "领导批示办理",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconbianzu19",
    routeName: "",
  },
  {
    uid: "331",
    resourceName: "接收上级批示",
    parentUid: "3",
    resourceLayer: 3,
    style: "",
    routeName: "acceptLeaderInstructions",
  },
  {
    uid: "332",
    resourceName: "查询批示反馈",
    parentUid: "3",
    resourceLayer: 3,
    style: "",
    routeName: "queryInstructFeedback",
  },
  {
    uid: "333",
    resourceName: "查询批示下发",
    parentUid: "3",
    resourceLayer: 3,
    style: "",
    routeName: "queryInstructHairdown",
  },
  
  // 编排班查询
  {
    uid: "4",
    resourceName: "编排班查询",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconbianzu17",
    routeName: "",
  },
  {
    uid: "401",
    resourceName: "浏览值班表",
    parentUid: "4",
    resourceLayer: 3,
    style: "el-icon-document",
    routeName: "browseDuty",
  },
  {
    uid: "402",
    resourceName: "下级值班表",
    parentUid: "4",
    resourceLayer: 3,
    style: "el-icon-document",
    routeName: "lowerLevelDuty",
  },
  
  // 通讯录查询
  {
    uid: "5",
    resourceName: "通讯录查询",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconbianzu20",
    routeName: "",
  },
  {
    uid: "51",
    resourceName: "人员通讯录",
    parentUid: "5",
    resourceLayer: 3,
    style: "el-icon-set-up",
    routeName: "personnelAddressQuery",
  },
  {
    uid: "52",
    resourceName: "单位通讯录",
    parentUid: "5",
    resourceLayer: 3,
    style: "el-icon-set-up",
    routeName: "companyAddressQuery",
  },
  // 通知公告
  {
    uid: "6",
    resourceName: "通知公告",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconbianzu21",
    routeName: "",
  },
  {
    uid: "61",
    resourceName: "下发通知公告",
    parentUid: "6",
    resourceLayer: 3,
    style: "el-icon-set-up",
    routeName: "issueNotice",
  },
  {
    uid: "62",
    resourceName: "接收通知公告",
    parentUid: "6",
    resourceLayer: 3,
    style: "el-icon-set-up",
    routeName: "receiveNotice",
  },
  {
    uid: "63",
    resourceName: "查询通知公告",
    parentUid: "6",
    resourceLayer: 3,
    style: "el-icon-set-up",
    routeName: "querryNotice",
  },
  // 文电拟办
  {
    uid: "7",
    resourceName: "文电拟办",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconbianzu22",
    routeName: "",
  },
  {
    uid: "371",
    resourceName: "来文拟办",
    parentUid: "7",
    resourceLayer: 3,
    style: "",
    routeName: "proposedCommunication",
  },
  {
    uid: "372",
    resourceName: "来电拟办",
    parentUid: "7",
    resourceLayer: 3,
    style: "",
    routeName: "callCommunication",
  },
  {
    uid: "373",
    resourceName: "电话记录",
    parentUid: "7",
    resourceLayer: 3,
    style: "",
    routeName: "telephoneRecords",
  },

 // 编排班管理
  {
    uid: "8",
    resourceName: "编排班管理",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconbianzu17",
    routeName: "",
  },
  {
    uid: "811",
    resourceName: "编排值班",
    parentUid: "8",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "editDuty",
  },
  {
    uid: "812",
    resourceName: "浏览值班表",
    parentUid: "8",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "browseDutyList",
  },
  {
    uid: "813",
    resourceName: "换班管理",
    parentUid: "8",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "shiftManage",
  },
  {
    uid: "814",
    resourceName: "替班管理",
    parentUid: "8",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "substituteManage",
  },
   // 通讯录管理
   {
    uid: "9",
    resourceName: "通讯录管理",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont icon33",
    routeName: "",
  },
   // 通讯录管理
   {
    uid: "91",
    resourceName: "单位通讯录",
    parentUid: "9",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "unitAddressBook",
  },
   // 通讯录管理
   {
    uid: "92",
    resourceName: "人员通讯录",
    parentUid: "9",
    resourceLayer: 3,
    style: "iconfont icon33",
    routeName: "personAddressBook",
  },
   // 用户管理
   {
    uid: "10",
    resourceName: "用户管理",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconzu11",
    routeName: "",
  },
  {
    uid: "101",
    resourceName: "本级用户",
    parentUid: "10",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "sameLevelUser",
  },
  {
    uid: "101",
    resourceName: "下级管理员",
    parentUid: "10",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "lowerLevelAdmin",
  },
   // 系统设置
   {
    uid: "11",
    resourceName: "系统设置",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconzu12",
    routeName: "",
  },
  {
    uid: "111",
    resourceName: "职务管理",
    parentUid: "11",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "jobManagement",
  },{
    uid: "112",
    resourceName: "级别管理",
    parentUid: "11",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "levelManagement",
  },{
    uid: "113",
    resourceName: "敏感日设置",
    parentUid: "11",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "sensitiveSetting",
  },
  {
    uid: "114",
    resourceName: "事件快报设置",
    parentUid: "11",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "eventExpressSetting",
  },
   // 系统管理
  {
    uid: "12",
    resourceName: "系统管理",
    parentUid: "0",
    resourceLayer: 2,
    style: "iconfont iconzu12",
    routeName: "",
  },
  // 组织机构
  {
    uid: "121",
    resourceName: "组织机构",
    parentUid: "12",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "unitManagement",
  },
  // 用户管理
  {
    uid: "122",
    resourceName: "用户管理",
    parentUid: "12",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "userManagement",
  },
  // 角色管理
  {
    uid: "123",
    resourceName: "角色管理",
    parentUid: "12",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "roleManagement",
  },
  // 权限管理
  {
    uid: "124",
    resourceName: "权限管理",
    parentUid: "12",
    resourceLayer: 3,
    style: "el-icon-film",
    routeName: "rightManagement",
  },
  
]



